name: firey_chat
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  google_sign_in:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  loading_animation_widget: ^1.2.0+4
  awesome_dialog: ^3.2.0
  flutter_otp_text_field: ^1.1.1
  shared_preferences:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/
